# Generated by Django 5.1.7 on 2025-04-07 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_owner_contactgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit Indian number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('owner', 'phone_number'), name='unique_phone_per_user'),
        ),
    ]
